-- ═══════════════════════════════════════════════════
-- LANGKAH 1: HAPUS DATA LAMA + IMPORT 210 PRODUK
-- Stok awal: 100 untuk semua (bibit 100ml, botol 100pcs)
-- ═══════════════════════════════════════════════════

-- HAPUS data lama (urutan penting: anak dulu, baru induk)
DELETE FROM transaksi_item WHERE transaksi_id IN (SELECT id FROM transaksi WHERE toko_id = (SELECT id FROM toko LIMIT 1));
DELETE FROM transaksi WHERE toko_id = (SELECT id FROM toko LIMIT 1);
DELETE FROM stok_movement WHERE toko_id = (SELECT id FROM toko LIMIT 1);
DELETE FROM varian WHERE produk_id IN (SELECT id FROM produk WHERE toko_id = (SELECT id FROM toko LIMIT 1));
DELETE FROM produk WHERE toko_id = (SELECT id FROM toko LIMIT 1);

-- INSERT 210 produk (stok = 100)
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Ariana grande sweet candy  PREMIUM', 'STOCK PARFUME', 900.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Annasui fantasy mermaid   PREMIUM', 'STOCK PARFUME', 1000.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Annasui fency flaghtPREMIUM', 'STOCK PARFUME', 900.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Alesha zahra   PREMIUM', 'STOCK PARFUME', 1300.0, 100, 50, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Aigner black PREMIUM', 'STOCK PARFUME', 1500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Aigner blue PREMIUM', 'STOCK PARFUME', 900.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Aigner debut PREMIUM', 'STOCK PARFUME', 900.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Aigner in leather PREMIUM', 'STOCK PARFUME', 900.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Baccarat Rouge PREMIUM', 'STOCK PARFUME', 1000.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Binggo jackpot PREMIUM', 'STOCK PARFUME', 1000.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT CH Good Girl PREMIUM', 'STOCK PARFUME', 900.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Chanel Allure PREMIUM', 'STOCK PARFUME', 1000.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Chloe Chloe PREMIUM', 'STOCK PARFUME', 1000.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Ch 212 man PREMIUM', 'STOCK PARFUME', 900.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Ch 212 VIP man PREMIUM', 'STOCK PARFUME', 900.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Cerruti PREMIUM', 'STOCK PARFUME', 1300.0, 100, 50, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Dior sauvage  PREMIUM', 'STOCK PARFUME', 1000.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Dunhill blue PREMIUM', 'STOCK PARFUME', 1300.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Escada Miami blossom PREMIUM', 'STOCK PARFUME', 800.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Gucci bambo PREMIUM', 'STOCK PARFUME', 1000.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT G.armani PREMIUM', 'STOCK PARFUME', 900.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Gucci guilty gold  PREMIUM', 'STOCK PARFUME', 800.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Golden Vinci PREMIUM', 'STOCK PARFUME', 800.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Hermes Tere PREMIUM', 'STOCK PARFUME', 1200.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Hajar Aswad PREMIUM', 'STOCK PARFUME', 800.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Kirhe tiziana PREMIUM', 'STOCK PARFUME', 1000.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Lv ombre PREMIUM', 'STOCK PARFUME', 900.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Lv rose PREMIUM', 'STOCK PARFUME', 1200.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Lv dancing PREMIUM', 'STOCK PARFUME', 900.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT lacoste essential PREMIUM', 'STOCK PARFUME', 1000.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Marcadez  bendz PREMIUM', 'STOCK PARFUME', 1000.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Mis Dior  PREMIUM', 'STOCK PARFUME', 1000.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Memo marfa S.O.T.B PREMIUM', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Nina Rici PREMIUM', 'STOCK PARFUME', 900.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Pacorabane olymp PREMIUM', 'STOCK PARFUME', 900.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Prada most PREMIUM', 'STOCK PARFUME', 800.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Scarlett Shasa PREMIUM', 'STOCK PARFUME', 1300.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Vs.sandalous PREMIUM', 'STOCK PARFUME', 1500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Vs.pomegranate LotusPREMIUM', 'STOCK PARFUME', 1300.0, 100, 50, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Vs.romantic wish PREMIUM', 'STOCK PARFUME', 800.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Versace Eros flame PREMIUM', 'STOCK PARFUME', 1000.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Roja Elysum  PREMIUM', 'STOCK PARFUME', 1000.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT vs aqua kiss  PREMIUM', 'STOCK PARFUME', 1000.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT 212 sexy man  PREMIUM', 'STOCK PARFUME', 1000.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Ysl black opium PREMIUM', 'STOCK PARFUME', 1000.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Azaroh', 'STOCK PARFUME', 800.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Al - madinah', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Annasui rose fancy', 'STOCK PARFUME', 800.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT  Avril', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Angel heart', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Annasui dream', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Aril implus', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Aqua man', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Aigner debut', 'STOCK PARFUME', 800.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Aigner blue emotion', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Aigner feminim', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Ashanti', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Arabian Swift', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Arianna grande', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Axe coklat', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Aigner black', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Bulgari Aqua', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Bulgaria extrime', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Bulgari Omnia', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Body shop Oceanus', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Body shop japanes', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Body shop vanila', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Baccarat', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Britney fantasy', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Bulgari rose', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Body shop white musk', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Beneton pink', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Bond no 9', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Barcelona', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Blue ice', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Britney midnight', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Buble gum', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Casablanca', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Coco Chanel', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Coffe maciato', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Cran berry', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Creed adventus', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Channel chance', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Channel 05', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Channel blue', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Ck one', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Clinique happy man', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Coffe black', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Coffe bali', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Cappucino', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Cristina Aguilera', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT D&g light blue', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Dunhill red', 'STOCK PARFUME', 800.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Davidof man', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Davidof cool water', 'STOCK PARFUME', 800.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Diamor women', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT D&g man', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Dunhill blue', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Dior sauvage', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Escada sexy gravity', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Enternity women', 'STOCK PARFUME', 800.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Escada Chery', 'STOCK PARFUME', 800.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Elizabeth avenue', 'STOCK PARFUME', 800.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Escada moon', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Enternity men', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Ferari black', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Fairytale', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Gucci flora', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Gucci gulty black', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Green tea', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Gucci blom', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Gucci bambo', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Gucci rush', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Guess pink', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Gucci envy', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Good Girl', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Hermes', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Hugo boss magnetik', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Hugo bos orange', 'STOCK PARFUME', 800.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Hugo boss xx', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Hugo bos energize', 'STOCK PARFUME', 800.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Harazuku japan love', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Isseye miayake', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Jlo platinum', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Jlo stil', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Jaguar Blue', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Jaguar vision', 'STOCK PARFUME', 800.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Juicy counture vivala juley', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Justin biber', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Jamalone English spear', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Jesika Parker', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Kasturi kijang brud', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Kenzo Bali', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Kenzo batang', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Kenzo daun', 'STOCK PARFUME', 700.0, 100, 50, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Kenzo leo par', 'STOCK PARFUME', 700.0, 100, 50, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Kasturi Putih', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Lacoste sport', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Lamborghini borju', 'STOCK PARFUME', 800.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Lovely', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Lifeboy', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Lancomballe', 'STOCK PARFUME', 400.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Mistioriza fantasy', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Mis Dior blooming', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Melon', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Marc jacob daisy', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Maherzein', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Malaki muzafar', 'STOCK PARFUME', 300.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Malaikat subuh', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Melati', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Nagita Slavina', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Nina Rici', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT One direction', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Ola Ramlan', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Pramugari', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Pink chiffon', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Paris hilton heires', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Phantom', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Pop cornn caramel', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Pacorabanne Invictus', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Pacorabanne jayrose grey', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Polo sport', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Rafi Ahmad', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Strawberry', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Selina Gomes', 'STOCK PARFUME', 450.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Soft', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Seribu bunga', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Silver', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Tissue', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Tutti fruity', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Turky Swift', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Taylor Swift', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Vanilla coffe', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Vanilla', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Victoria Lady', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT vs.romantic wish', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Vs.sacndalous', 'STOCK PARFUME', 650.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Vs.aqua kis', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Vs.so sexy', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Vs.bom shel', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Vs.coconut passion', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Victoria black to pink', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Vanila susu', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Vanila coklat', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Vanila late', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Vanila manggo', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Vanila Ice', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Versace Eros man', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Ysl liber', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Ysl black opium', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Ysl moon pariss', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Yellow amber', 'STOCK PARFUME', 400.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Zara man', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Zara red vanila', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Zara Wonde rose', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Zara love', 'STOCK PARFUME', 700.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Zara Orchid', 'STOCK PARFUME', 500.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'BIBIT Zara women', 'STOCK PARFUME', 600.0, 100, 50.0, 'ml' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'STOK BOTOL ULIR 4ML', 'STOK BOTOL', 1000.0, 100, 30.0, 'pcs' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'STOK BOTOL ULIR 10ML', 'STOK BOTOL', 1500.0, 100, 30.0, 'pcs' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'STOK BOTOL 15ML', 'STOK BOTOL', 2500.0, 100, 30.0, 'pcs' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'STOK BOTOL 20ML', 'STOK BOTOL', 3000.0, 100, 30.0, 'pcs' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'STOK BOTOL 25ML', 'STOK BOTOL', 4000.0, 100, 30.0, 'pcs' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'STOK BOTOL 30ML', 'STOK BOTOL', 5600.0, 100, 30.0, 'pcs' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'STOK BOTOL 35ML', 'STOK BOTOL', 5600.0, 100, 30.0, 'pcs' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'STOK BOTOL 40ML', 'STOK BOTOL', 5600.0, 100, 30.0, 'pcs' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'STOK BOTOL 50ML', 'STOK BOTOL', 6000.0, 100, 30.0, 'pcs' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'STOK BOTOL 55ML', 'STOK BOTOL', 6000.0, 100, 30.0, 'pcs' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'STOK BOTOL 60ML', 'STOK BOTOL', 6000.0, 100, 30.0, 'pcs' FROM toko LIMIT 1;
INSERT INTO produk (toko_id, nama, kategori, harga_beli, stok, min_stok, satuan) SELECT id, 'STOK BOTOL 100ML', 'STOK BOTOL', 7000.0, 100, 30.0, 'pcs' FROM toko LIMIT 1;